### ISSUE TITLE
Cannot build with cmake 4

### ISSUE THREAD

**Issue by ngoldbaum** [honzasp/rust-turbojpeg#30]
If I try to do e.g. `cargo test` using the recently released cmake 4.0.0, I see:

```
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 has been removed from CMake.

    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
    to tell CMake that the project requires at least <min> but has been updated
    to work with policies introduced by <max> or earlier.

    Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```

I don't see this manually building libjpeg-turbo, not sure what the difference here is.

**Comment by ngoldbaum** [comment]
Oh I guess it's because the submodule is pinned to a version of libjpeg-turbo from two years ago.

**Comment by PuffyWithEyes** [comment]
When is the release `1.3.1`?

**Comment by honzasp** [comment]
Hi, I just merged https://github.com/honzasp/rust-turbojpeg/pull/29 and released a new version 1.3.1, could you please check whether it fixes your issue?

**Comment by ngoldbaum** [comment]
I still get the same error after I pull and update to the latest `master` branch. Did you typo the submodule update? It's at 3.0.1 now. If I manually update to 3.1.0 then I can build turbojpeg and run the cargo tests.

```diff
diff --git a/turbojpeg-sys/libjpeg-turbo b/turbojpeg-sys/libjpeg-turbo
index ec32420..20ade4d 160000
--- a/turbojpeg-sys/libjpeg-turbo
+++ b/turbojpeg-sys/libjpeg-turbo
@@ -1 +1 @@
-Subproject commit ec32420f6b5dfa4e86883d42b209e8371e55aeb5
+Subproject commit 20ade4dea9589515a69793e447a6c6220b464535
```

**Comment by Aemulation** [comment]
I also still get the same error.
I believe 65dede2c7085067c984ce8d9b018939d1bf55393 somehow reverted the submodule update from #29.

**Comment by honzasp** [comment]
Oops, looks like I made a mistake! I released new version 1.3.2 which should fix that.

**Comment by Aemulation** [comment]
It works for me, thanks!

**Comment by ngoldbaum** [comment]
This is fixed now
